export enum EspecialidadeMedica {
  PNEUMOLOGIA = 'PNEUMOLOGIA',
  IMUNOALERGOLOGIA = 'IMUNOALERGOLOGIA',
  MEDICINA_GERAL_FAMILIAR = 'MEDICINA_GERAL_FAMILIAR',
  PEDIATRIA = 'PEDIATRIA',
  OTORRINOLARINGOLOGIA = 'OTORRINOLARINGOLOGIA',
  MEDICINA_INTERNA = 'MEDICINA_INTERNA',
}
