export enum TipoExame {
  ESPIROMETRIA = 'ESPIROMETRIA',
  RADIOGRAFIA_TORAX = 'RADIOGRAFIA_TORAX',
  TOMOGRAFIA_TORAX = 'TOMOGRAFIA_TORAX',
  OXIMETRIA = 'OXIMETRIA',
  GASOMETRIA = 'GASOMETRIA',
  RINOSCOPIA = 'RINOSCOPIA',
  TESTE_ALERGICOS = 'TESTE_ALERGICOS',
  PEAK_FLOW = 'PEAK_FLOW',
  NEBULIZACAO = 'NEBULIZACAO',
  OUTRO = 'OUTRO',
}
