export enum ViaAdministracao {
  ORAL = 'ORAL',
  INALADA = 'INALADA',
  INTRAVENOSA = 'INTRAVENOSA',
  SUBCUTANEA = 'SUBCUTANEA',
  TOPICA = 'TOPICA',
  NASAL = 'NASAL',
  NEBULIZACAO = 'NEBULIZACAO',
}
